import Head from 'next/head'
import { PageLayout } from '@/components/layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <div className="flex h-full w-full flex-col flex-wrap items-center justify-center gap-10 border-amber-300">
          <div id='home-element' className="h-10 w-full text-center text-5xl font-bold text-gray-900">
            Next js
          </div>
        </div>
      </PageLayout>
    </>
  )
}
